/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package j.adt;

import j.adt.Option.Some;

public class App {

    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(divide(9, 3).combine(App::successResult, App::failureResult));
        System.out.println(divide(9, 0).combine(App::successResult, App::failureResult));
    }

    public static String successResult(Option.Some<Integer> s) {
        return String.format("result was: %d", s.getValue());
    }

    public static String failureResult(Option.None<Integer> s) {
        return "divide by 0";
    }

    public static Option<Integer> divide(int x, int y) {
        if (y == 0) {
            return new Option.None<>();
        }
        return new Option.Some<>(x / y);
    }
}
